'use client';

import React, { useState } from 'react';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import UserDashboardLayout from '@/components/dashboard/UserDashboardLayout';
import CycloneMapLibre from '@/components/map/CycloneMapLibre';
import StatusBadge from '@/components/dashboard/StatusBadge';
import { useDashboard } from '@/context/DashboardContext';
import { RiskRegion } from '@/types/cyclone';
import { ShieldAlert, Wind, CloudRain, Waves, Users, AlertTriangle } from 'lucide-react';

function RiskMapContent() {
  const { currentRiskRegions, flyToLocation } = useDashboard();
  const [selectedRegion, setSelectedRegion] = useState<RiskRegion | null>(currentRiskRegions[0] || null);

  const activeReg = selectedRegion || currentRiskRegions[0] || {
    id: 'risk_odisha_north',
    regionName: 'Northern Coastal Odisha (Bhadrak / Balasore)',
    stateCountry: 'Odisha, India',
    riskLevel: 'CRITICAL',
    windRiskScore: 94,
    rainfallRiskScore: 90,
    stormSurgeMeters: 4.5,
    coastalExposureScore: 96,
    populationExposure: '2.8 Million',
    primaryCycloneId: 'cyc_aruna',
    primaryCycloneName: 'Cyclone Aruna',
    lastUpdated: '08:15 UTC (DEMO)',
    coordinates: [],
    summary: 'Extreme wind gusts > 150 km/h and astronomical storm surge peak of 4.5m expected near Dhamra and Chandipur coastal zones.',
  };

  const handleSelectRegion = (reg: RiskRegion) => {
    setSelectedRegion(reg);
    if (reg.coordinates && reg.coordinates.length > 0) {
      flyToLocation(reg.coordinates[0], 7.0);
    }
  };

  return (
    <UserDashboardLayout>
      <div className="space-y-6 select-none font-mono text-xs">
        {/* MANDATORY AI ASSISTED RISK ASSESSMENT DISCLAIMER BANNER */}
        <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/40 text-amber-300 text-xs flex items-start gap-3 shadow-md">
          <AlertTriangle className="h-5 w-5 shrink-0 text-amber-400 mt-0.5" />
          <div>
            <span className="font-bold uppercase tracking-wider block mb-0.5">
              AI-ASSISTED RISK ASSESSMENT (DEMO) - NOT AN OFFICIAL GOVERNMENT WARNING
            </span>
            <p className="text-slate-300 leading-relaxed font-sans text-xs">
              Spatial risk layers presented on this map are generated by deep learning hydrodynamic surge models and ensemble wind fields. Always consult official meteorological agency bulletins (IMD, JTWC, WMO) for evacuation and emergency decision-making.
            </p>
          </div>
        </div>

        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-6 rounded-3xl bg-[#091126] border border-slate-800 shadow-xl">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-amber-400 font-bold uppercase tracking-wider flex items-center gap-1.5">
                <ShieldAlert className="h-4 w-4" /> Coastal Inundation & Hazard
              </span>
              <span className="px-2 py-0.5 rounded text-[9px] bg-amber-500/20 text-amber-300 border border-amber-500/40 font-bold">
                DEMO DATA
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              Coastal Hazard, Storm Surge & Risk Mapping
            </h1>
            <p className="text-xs text-slate-400 mt-1">
              Probabilistic impact mapping across high-vulnerability coastal districts and riverine deltas.
            </p>
          </div>
        </div>

        {/* Split View: GIS Risk Map + Region Detail Panel */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* GIS Risk Map Viewport (7 Cols) */}
          <div className="lg:col-span-7 h-[540px] rounded-3xl overflow-hidden border border-slate-800 shadow-2xl bg-[#060b19]">
            <CycloneMapLibre className="w-full h-full" />
          </div>

          {/* Region Factor Breakdown (5 Cols) */}
          <div className="lg:col-span-5 space-y-4">
            <h3 className="font-bold text-white uppercase tracking-wider text-sm">
              Selected Coastal Zone Hazard Factors
            </h3>

            <div className="p-6 rounded-3xl bg-[#091126] border border-slate-800 space-y-5 shadow-xl">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <h4 className="text-base font-extrabold text-white">{activeReg.regionName}</h4>
                  <span className="text-xs text-slate-400">{activeReg.stateCountry}</span>
                </div>
                <StatusBadge status={activeReg.riskLevel} />
              </div>

              {/* Progress Factors */}
              <div className="space-y-3.5 pt-2 border-t border-slate-800/80 text-xs">
                {/* Wind Hazard */}
                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><Wind className="h-3.5 w-3.5 text-cyan-400" /> Wind Hazard Score</span>
                    <strong className="text-white">{activeReg.windRiskScore}/100</strong>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-cyan-400 rounded-full" style={{ width: `${activeReg.windRiskScore}%` }} />
                  </div>
                </div>

                {/* Rainfall Hazard */}
                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><CloudRain className="h-3.5 w-3.5 text-blue-400" /> Rainfall Exposure</span>
                    <strong className="text-white">{activeReg.rainfallRiskScore}/100</strong>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-blue-400 rounded-full" style={{ width: `${activeReg.rainfallRiskScore}%` }} />
                  </div>
                </div>

                {/* Storm Surge Peak */}
                <div className="flex items-center justify-between p-3 rounded-2xl bg-[#060b19] border border-slate-800">
                  <span className="flex items-center gap-2 text-slate-300">
                    <Waves className="h-4 w-4 text-teal-400" /> Peak Astronomical Surge
                  </span>
                  <span className="text-cyan-300 font-black text-sm">{activeReg.stormSurgeMeters} meters</span>
                </div>

                {/* Population Exposure */}
                <div className="flex items-center justify-between p-3 rounded-2xl bg-[#060b19] border border-slate-800">
                  <span className="flex items-center gap-2 text-slate-300">
                    <Users className="h-4 w-4 text-amber-400" /> Coastal Population Exposure
                  </span>
                  <span className="text-amber-300 font-black text-sm">{activeReg.populationExposure}</span>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed bg-[#060b19] p-3 rounded-2xl border border-slate-800">
                {activeReg.summary}
              </p>

              {/* Coastal Zone Switcher */}
              <div className="pt-3 border-t border-slate-800 space-y-2">
                <span className="text-[10px] text-slate-500 uppercase font-bold block">Switch Coastal Region:</span>
                <div className="space-y-1.5">
                  {currentRiskRegions.map((rr) => (
                    <button
                      key={rr.id}
                      onClick={() => handleSelectRegion(rr)}
                      className={`w-full text-left p-2.5 rounded-2xl text-xs transition-colors flex items-center justify-between border ${
                        activeReg.id === rr.id
                          ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/50 font-bold shadow-sm'
                          : 'bg-[#060b19] text-slate-400 border-slate-800 hover:text-white hover:bg-slate-800/40'
                      }`}
                    >
                      <span className="truncate pr-2">{rr.regionName}</span>
                      <StatusBadge status={rr.riskLevel} size="sm" />
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </UserDashboardLayout>
  );
}

export default function RiskMapPage() {
  return (
    <ProtectedRoute requiredRole="USER">
      <RiskMapContent />
    </ProtectedRoute>
  );
}
