'use client';

import React, { useState } from 'react';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import UserDashboardLayout from '@/components/dashboard/UserDashboardLayout';
import MapPanel from '@/components/map/MapPanel';
import StatusBadge from '@/components/dashboard/StatusBadge';
import { useRisk } from '@/hooks/useCycloneData';
import { RiskRegion } from '@/lib/mock/riskMock';
import { AlertTriangle, ShieldAlert, Wind, CloudRain, Waves, Users } from 'lucide-react';

function RiskMapContent() {
  const { riskRegions } = useRisk();
  const [selectedRegion, setSelectedRegion] = useState<RiskRegion>(riskRegions[0] || {
    id: 'risk_orissa_north',
    regionName: 'Northern Coastal Odisha (Bhadrak / Balasore)',
    stateCountry: 'Odisha, India',
    riskLevel: 'CRITICAL',
    windRiskScore: 92,
    rainfallRiskScore: 88,
    stormSurgeMeters: 4.2,
    coastalExposureScore: 95,
    populationExposure: '2.4 Million',
    primaryCycloneId: 'cyc_aruna',
    lastUpdated: '2026-08-31 03:00 UTC',
  });

  return (
    <UserDashboardLayout>
      <div className="space-y-6 select-none">
        {/* MANDATORY AI ASSISTED RISK ASSESSMENT DISCLAIMER BANNER */}
        <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/40 text-amber-300 text-xs flex items-start gap-3 shadow-md">
          <AlertTriangle className="h-5 w-5 shrink-0 text-amber-400 mt-0.5" />
          <div>
            <span className="font-mono font-bold uppercase tracking-wider block mb-0.5">
              AI-ASSISTED RISK ASSESSMENT (DEMO) - NOT AN OFFICIAL GOVERNMENT WARNING
            </span>
            <p className="text-slate-300 leading-relaxed">
              Spatial risk layers presented on this map are generated by deep learning model projections. Always consult official meteorological agency bulletins (IMD, JTWC, WMO) for evacuation & emergency decision-making.
            </p>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
              <ShieldAlert className="h-6 w-6 text-amber-400" />
              <span>Coastal Hazard & Surge Risk Map</span>
              <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-amber-500/20 text-amber-300 border border-amber-500/40 font-bold">
                DEMO DATA
              </span>
            </h1>
            <p className="text-xs font-mono text-slate-400 mt-1">
              Probabilistic impact mapping across coastal landfalls and ocean basins.
            </p>
          </div>
        </div>

        {/* GIS Map & Region Risk Details Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* GIS Map Viewport */}
          <div className="lg:col-span-8">
            <MapPanel height="h-[460px]" showTitle={false} />
          </div>

          {/* Region Detail Card */}
          <div className="lg:col-span-4 space-y-4">
            <h3 className="text-sm font-mono font-bold text-white uppercase tracking-wider">
              Selected Region Risk Factors
            </h3>

            <div className="p-6 rounded-2xl bg-[#091024] border border-slate-800 space-y-5 shadow-xl">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-base font-bold text-white">{selectedRegion.regionName}</h4>
                  <span className="text-xs font-mono text-slate-400">{selectedRegion.stateCountry}</span>
                </div>
                <StatusBadge status={selectedRegion.riskLevel} />
              </div>

              {/* Risk Factors Breakdown */}
              <div className="space-y-3 pt-3 border-t border-slate-800 text-xs font-mono">
                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><Wind className="h-3.5 w-3.5 text-cyan-400" /> Wind Hazard Score</span>
                    <span className="font-bold text-white">{selectedRegion.windRiskScore}/100</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-cyan-400 rounded-full" style={{ width: `${selectedRegion.windRiskScore}%` }} />
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><CloudRain className="h-3.5 w-3.5 text-blue-400" /> Rainfall Exposure</span>
                    <span className="font-bold text-white">{selectedRegion.rainfallRiskScore}/100</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-blue-400 rounded-full" style={{ width: `${selectedRegion.rainfallRiskScore}%` }} />
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><Waves className="h-3.5 w-3.5 text-teal-400" /> Storm Surge Height</span>
                    <span className="font-bold text-cyan-300">{selectedRegion.stormSurgeMeters} meters</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between text-slate-300">
                    <span className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5 text-amber-400" /> Population Exposure</span>
                    <span className="font-bold text-amber-300">{selectedRegion.populationExposure}</span>
                  </div>
                </div>
              </div>

              {/* Region Selector List */}
              <div className="pt-3 border-t border-slate-800 space-y-2">
                <span className="text-[10px] font-mono text-slate-500 uppercase block">Switch Coastal Region:</span>
                <div className="space-y-1">
                  {riskRegions.map((rr) => (
                    <button
                      key={rr.id}
                      onClick={() => setSelectedRegion(rr)}
                      className={`w-full text-left p-2 rounded-xl text-xs font-mono transition-colors flex items-center justify-between ${
                        selectedRegion.id === rr.id
                          ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40'
                          : 'text-slate-400 hover:text-white hover:bg-slate-800'
                      }`}
                    >
                      <span className="truncate pr-2">{rr.regionName}</span>
                      <StatusBadge status={rr.riskLevel} size="sm" />
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </UserDashboardLayout>
  );
}

export default function RiskMapPage() {
  return (
    <ProtectedRoute requiredRole="USER">
      <RiskMapContent />
    </ProtectedRoute>
  );
}
